---
- name: Delete Docker resources
  hosts: localhost
  tasks:
    - name: Stop and remove containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - wordpress
        - proxy
        - database

    - name: Remove Docker networks
      docker_network:
        name: "{{ item }}"
        state: absent
      loop:
        - bridge
        - host
        - none
