version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"  # Change the external port from 80 to 8080
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: example_db

  proxy:
    image: nginx  # or use "image: apache" for Apache
    ports:
      - "8080:80"
      - "443:443"
      
  database:
    image: mariadb  # or use "image: mysql" for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
