version: '3.7'

services:
  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '8080:8080'  # Change to port 8080
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_DATABASE_PASSWORD: Universe1!
    volumes:
      - 'moodle_data:/bitnami/moodle'
    depends_on:
      - mariadb

  mariadb:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: Universe1!
      MYSQL_DATABASE: bitnami_moodle
    volumes:
      - 'mariadb_data:/var/lib/mysql'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'  # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
    depends_on:
      - moodle

  portainer:
    image: portainer/portainer:latest
    ports:
      - '9000:9000'  # Expose port 9000 for Portainer UI
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'  # Grant access to the Docker API
      - 'portainer_data:/data'  # Persist Portainer data
    restart: always

volumes:
  moodle_data:
    driver: local
  mariadb_data:
    driver: local
  portainer_data:
    driver: local
